/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DidntBuyRouteImport } from './routes/didnt-buy'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as PauseRouteImport } from './routes/pause'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StartRouteImport } from './routes/start'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as WinsRouteImport } from './routes/wins'
import { Route as ReviewIdRouteImport } from './routes/review.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DidntBuyRoute = DidntBuyRouteImport.update({
  id: '/didnt-buy',
  path: '/didnt-buy',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const PauseRoute = PauseRouteImport.update({
  id: '/pause',
  path: '/pause',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const WinsRoute = WinsRouteImport.update({
  id: '/wins',
  path: '/wins',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewIdRoute = ReviewIdRouteImport.update({
  id: '/review/$id',
  path: '/review/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/didnt-buy': typeof DidntBuyRoute
  '/insights': typeof InsightsRoute
  '/pause': typeof PauseRoute
  '/settings': typeof SettingsRoute
  '/start': typeof StartRoute
  '/waitlist': typeof WaitlistRoute
  '/wins': typeof WinsRoute
  '/review/$id': typeof ReviewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/didnt-buy': typeof DidntBuyRoute
  '/insights': typeof InsightsRoute
  '/pause': typeof PauseRoute
  '/settings': typeof SettingsRoute
  '/start': typeof StartRoute
  '/waitlist': typeof WaitlistRoute
  '/wins': typeof WinsRoute
  '/review/$id': typeof ReviewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/didnt-buy': typeof DidntBuyRoute
  '/insights': typeof InsightsRoute
  '/pause': typeof PauseRoute
  '/settings': typeof SettingsRoute
  '/start': typeof StartRoute
  '/waitlist': typeof WaitlistRoute
  '/wins': typeof WinsRoute
  '/review/$id': typeof ReviewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/didnt-buy'
    | '/insights'
    | '/pause'
    | '/settings'
    | '/start'
    | '/waitlist'
    | '/wins'
    | '/review/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/didnt-buy'
    | '/insights'
    | '/pause'
    | '/settings'
    | '/start'
    | '/waitlist'
    | '/wins'
    | '/review/$id'
  id:
    | '__root__'
    | '/'
    | '/didnt-buy'
    | '/insights'
    | '/pause'
    | '/settings'
    | '/start'
    | '/waitlist'
    | '/wins'
    | '/review/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DidntBuyRoute: typeof DidntBuyRoute
  InsightsRoute: typeof InsightsRoute
  PauseRoute: typeof PauseRoute
  SettingsRoute: typeof SettingsRoute
  StartRoute: typeof StartRoute
  WaitlistRoute: typeof WaitlistRoute
  WinsRoute: typeof WinsRoute
  ReviewIdRoute: typeof ReviewIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/didnt-buy': {
      id: '/didnt-buy'
      path: '/didnt-buy'
      fullPath: '/didnt-buy'
      preLoaderRoute: typeof DidntBuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pause': {
      id: '/pause'
      path: '/pause'
      fullPath: '/pause'
      preLoaderRoute: typeof PauseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wins': {
      id: '/wins'
      path: '/wins'
      fullPath: '/wins'
      preLoaderRoute: typeof WinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$id': {
      id: '/review/$id'
      path: '/review/$id'
      fullPath: '/review/$id'
      preLoaderRoute: typeof ReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DidntBuyRoute: DidntBuyRoute,
  InsightsRoute: InsightsRoute,
  PauseRoute: PauseRoute,
  SettingsRoute: SettingsRoute,
  StartRoute: StartRoute,
  WaitlistRoute: WaitlistRoute,
  WinsRoute: WinsRoute,
  ReviewIdRoute: ReviewIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
